name: ${pom.name}
main: ${plugin.main}
version: ${pom.version}
softdepend: [${plugin.softdepend}]
depend: [${plugin.depend}]
commands:
    forgepermittor:
        permission: forgepermittor.command
        aliases: [fp]